### ISSUE TITLE
Spawners break when inside a Player Vault

### ISSUE THREAD

**Issue by Adolfin** [drtshock/PlayerVaults#101] opened 2015-08-04 21:53 UTC
When you place a spawner inside a Player Vault it seems to set the spawner to the default pig spawner. If this isn't an issue with the plugin, is there anything I can do to fix this?

**Comment by drtshock** [comment] 2015-08-06 16:35
Duplicate of https://github.com/drtshock/PlayerVaults/issues/62

**Closed by drtshock** 2015-08-06 16:35 UTC
