### ISSUE TITLE
PlayerVaults deleting pvs randomly

### ISSUE THREAD

**Issue by ArmonicPvP** [drtshock/PlayerVaults#353] opened 2018-04-16 23:53 UTC
PlayerVaultsX version (run `/version playervaults`): 
4.0.5
Server software (run `/version`): 
PaperSpigot 1.8.8
Server (`logs/latest.log`):
Nothing shows about it in the logs.
Details:
Players seem to be having their PVs randomly delete. Players will run /pv (x number) and the PV will fail to show up. Next, if they try /pv (any number) the PV won't show up at all, and there is no message in the chat from the plugin. When they relog and do /pv (x number), that pv is completely empty.

**Comment by blijgozertje** [comment] 2018-09-28 19:16
^ Having this too now

**Comment by Golicraft** [comment] 2018-10-04 15:38
This needs to be fixed @drtshock It happend again with another player! :-1:

**Comment by ArmonicPvP** [comment] 2018-10-04 15:51
Are you all using CrazyEnchantments or are the players putting items with custom lore in their PVs? This breaks the PVs.

**Comment by Golicraft** [comment] 2018-10-04 17:52
> Are you all using CrazyEnchantments or are the players putting items with custom lore in their PVs? This breaks the PVs.

Yes I use both. Custom lore and CrazyEnchantments. This needs to be fixed... 

I can't disable custom lores and that stuff.. but thanks. Now you confirmed that my theory was true (the lores that crash the pvs)

**Comment by ArmonicPvP** [comment] 2018-10-04 17:57
The issue is the way that the plugin tries to understand the lore messages. When it doesn't recognize it, it chooses to just clear the entire file. It should just display an error rather than wiping the PV. This issue needs to be resolved as well.

**Comment by Golicraft** [comment] 2018-10-04 18:20
The main issue here is that @drtshock doesn't reply. Last day he replied someone on the spigot threads (his rating for the plugin) but doesn't care for me tagging him 6 days ago... this is awful. We deserve a reply and a fix. I will understand if you are busy but just to reply to this thread is good enough. Then we know there will be a fix soon. But no, he hasn't! I will wait patiently like 3-5 more days. After that, I will probably make a bad review and warn anybody about this issue. Also if this will not be fixed soon I need to change plugin and then this was kind of wase of money.

**Comment by drtshock** [comment] 2018-10-04 18:29
I've been chatting with some people in discord about this issue and the problem is that I'm unable to reproduce it.

**Comment by Golicraft** [comment] 2018-10-04 18:35
No it isn't something to reproduce. it happens some random time.. I do not know what trigger the event to handle. I can join the discord and chat further.

**Comment by Xenthyk** [comment] 2019-01-20 23:57
This just happened to me using version 4.1.0. The backup was from a few minutes prior so it was corrupted also. Good thing I had a snapshot from 3 days ago that was close enough for the player. If this is an issue I would like to see more backup options. Im not sure when it was wiped since there isnt any error in PlayerVaults. It was wiped with the following value in the problem valut. 

rO0ABXcEAAAANnBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBw
  cHBwcHBwcA==

**Comment by ReimannMC** [comment] 2019-07-31 19:39
Bump.

**Comment by BrettplayMC** [comment] 2019-08-29 05:10
Same issue, I also have CrazyEnchantments.

**Comment by CmdrKittens** [comment] 2020-03-30 14:52
I believe this is resolved in the latest release. The issue, as we found it, came down to some plugins making modifications to items in ways that the server itself did not like. These invalid items would then break PV's attempt at storage.

**Closed by CmdrKittens** 2020-03-30 14:52 UTC
