### ISSUE TITLE
error when trying to view players vaults

### ISSUE THREAD

**Issue by Twi5TeD** [drtshock/PlayerVaults#227] opened 2016-09-03 13:37 UTC
`[13:33:53 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pv' in plugin PlayerVaults v3.6.0-SNAPSHOT-b202
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"65fd35f"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"65fd35f"]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NumberFormatException: For input string: "rubricals"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_101]
        at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:63) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        ... 15 more`
this is caused when i try doing /pv 1 name also the playervaults dont show any content when opened

**Comment by DataStoreRBLX** [comment] 2016-09-11 08:12
Exactly the same problem occurring on our server, running the latest development build available. On top of #215.

Unsure on the cause of this, as I've gone through their Player Vault in the save file, and there's literally nothing odd; some armour and that's about it. Equally, as an admin, I'm unable to open or see their Player Vault.

**Comment by kashike** [comment] 2016-09-11 08:24
You're not on the latest version, @Twi5TeD.
@DataStoreRBLX: Stacktrace, please.

**Comment by DataStoreRBLX** [comment] 2016-09-13 19:56
@kashike 
Apologies for a slow response; GitHub didn't really keep me up to date. 

```
[01:04:47] [Server thread/INFO]: josephsigmar issued server command: /pv 1
[01:04:47] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pv' in plugin PlayerVaults v3.6.0-SNAPSHOT-b207
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[Paper.jar:git-Paper-842]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[Paper.jar:git-Paper-842]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:665) ~[Paper.jar:git-Paper-842]
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [Paper.jar:git-Paper-842]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1194) [Paper.jar:git-Paper-842]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Paper.jar:git-Paper-842]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [Paper.jar:git-Paper-842]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Paper.jar:git-Paper-842]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [Paper.jar:git-Paper-842]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:791) [Paper.jar:git-Paper-842]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [Paper.jar:git-Paper-842]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725) [Paper.jar:git-Paper-842]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624) [Paper.jar:git-Paper-842]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_77]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463) ~[?:1.8.0_77]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461) ~[?:1.8.0_77]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:151) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:157) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:102) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:161) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOwnVault(UUIDVaultManager.java:101) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:150) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:175) ~[?:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:35) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Paper.jar:git-Paper-842]
	... 15 more
```

**Comment by DataStoreRBLX** [comment] 2016-09-15 16:29
I've also seen certain user's error reports get lambasted after they've used various forks of the same server software. Due to that, this was also tested on a clean version of Spigot - Yielding the exact same error. 

```
[17:23:30] [Server thread/INFO]: Faxed issued server command: /pv 1
[17:23:30] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pv' in plugin PlayerVaults v3.6.0-SNAPSHOT-b207
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot.jar:git-Spigot-570526c-75a8885]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot.jar:git-Spigot-570526c-75a8885]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[Spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358) [Spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193) [Spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot.jar:git-Spigot-570526c-75a8885]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_73]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [Spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [Spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [Spigot.jar:git-Spigot-570526c-75a8885]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [Spigot.jar:git-Spigot-570526c-75a8885]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_73]
	at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_73]
	at java.util.HashMap$EntryIterator.next(Unknown Source) ~[?:1.8.0_73]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:151) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.deserialize(Serialization.java:157) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.toInventory(Serialization.java:102) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.getInventory(UUIDVaultManager.java:161) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.loadOwnVault(UUIDVaultManager.java:101) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:150) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.VaultOperations.openOwnVault(VaultOperations.java:175) ~[?:?]
	at com.drtshock.playervaults.commands.VaultCommand.onCommand(VaultCommand.java:35) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot.jar:git-Spigot-570526c-75a8885]
	... 15 more
```

Upon trawling through the PV in question, and editing out each and every item and then replacing it, I found the following to be causing the issue for this vault:

```
 '15': '{"==":"org.bukkit.inventory.ItemStack","damage":75,"type":"DIAMOND_CHESTPLATE","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"PROTECTION_ENVIRONMENTAL":18,"DURABILITY":7,"Toughness":2,"KnockbackResistance":1,"THORNS":5},"internal":"H4sIAAAAAAAAAONiYOBkEHIsKSnKTCotSfXNT8lMy0wtKuZiYGBgZmHgCA31dPHNLy55NHEry9K5RmwsDJwgIZ\/UxOKS\/ZUdP021tu1gY2BzzM0vzSuxvxD4ulVuRxAHAy\/cRL\/E3FQG6fTUvNSizGS97Lz85OykxOTsoNTizOKSxLzkVGYGTv+C1KLEksz8PKClDBwMLGA9Et4ItSmlySBpRzDJMOosUpzFAABqBKRX4wEAAA==","lore":["§7Toughness
    §7II","§7KnockbackResistance §7I","","§8(§c!§8) §7Skip durability damage chance:
    §325%","§8(§c!§8) §7No knockback chance: §3+25%"],"display-name":"6Daedalus fChestplate","ItemFlags":["HIDE_ATTRIBUTES"],"repair-cost":3}}'
```

**Comment by drtshock** [comment] 2016-09-15 17:28
Can you get this to happen with items if you don't have any other plugins on the server other than playervaults?

**Comment by DataStoreRBLX** [comment] 2016-09-16 14:53
@drtshock 
Whilst that would generally be a helpful indicator, I'm unsure as to why an internal tag is even added in the first place - Whilst I thought it had something to do with a plugin, we had made on a 'custom' basis, other users are also experiencing similar issues (noted with the original reporter on this issue thread).

So, to answer your question, with no plugins on the server at all other than the minimum of Essentials, Vault, etc - The issue persists if we attempt to open a pre-existing vault which contains an item with the internal tag/flag. However, as to whether it occurs naturally, I've not the slightest idea - All I can say is that we went about nine months without an issue. It's not until moving to the latest, stable, developer build that we've ran into this issue.

**Comment by drtshock** [comment] 2016-09-16 18:21
We just use bukkit serialization so any internal tag would be a result of that. Odd that it would somehow show up but not be able to parse it later..

**Comment by frostalf** [comment] 2016-09-19 02:27
The internal tag is just a base64 encode of raw NBT data, essentially useless. I suspect the reason for the error is due to the fact the deserialization process doesn't do anything about the internal tag but does everything else with all the other tags. A possible solution would be to just have the internal tag removed if its present as it doesn't do anything to begin with. How it gets there is due to minecraft adding it. If I had some vault data, I could test the solution and then PR it.

**Comment by DataStoreRBLX** [comment] 2016-09-24 04:23
As further information, to this, I've just come across another user's vault with an internal tag - It seems to work fine, which is incredibly odd - considering it didn't work for the others. 

Essentially, this user has a full PlayerVault worth of spawners and other assorted items such as skulls - They've all had an internal tag pinned on them, but he has been using his vaults without fault. So at present it seems to be selectively affecting people - And, so far as tests go, for the six users who have had the problem all six have had it fixed by us manually removing the internal tag/internal tagged item.

Incredibly odd.

**Comment by frostalf** [comment] 2016-09-25 04:50
Only thing I can think of is where in the saved data is the internal key present. IE, is it at the end or is it in the middle? Either way, I think the best solution to the problem would be to just check for the internal tag and just remove it before saving the data, and on loading check for the internal tag and remove it if present.

**Comment by DataStoreRBLX** [comment] 2016-10-04 21:51
As a further update to this, on several occasions I've attempted to resolve a user's vault problem by removing the internal tags manually - However, the issue persists in most but not all circumstances.

This is an incredibly vexing issue, considering that the only thing linking together the items is the fact they had the internal tag at some time or another. However, as noted, some individuals have been using items with internal tags just fine - Looking past that, it appears that another common factor in most (but not all) cases is the presence of a HIDE-ATTRIBUTES tag. 

Upon removal of both the internal tag, and the 'HIDE-ATTRIBUTES' tag, the PVs are fixed in 100% of cases that I've now come across.

**Closed** 2017-04-24 18:59 UTC
Labels: bug

**Comment by Faxed** [comment] 2017-04-24 19:04
Right... So, isn't this very much just a case of burying your head in the sand? The issues tab is meant to make a note of issues, which Kashike just seemed to obliterate - There's issues outstanding since last year. Closing them all doesn't mean they're gone.

**Comment by kashike** [comment] 2017-04-24 19:09
Feel free to open issues that are still relevant. Not sure if they'll ever get looked into unless someone submits a pull request.
