### ISSUE TITLE
Corrupted Vaults

### ISSUE THREAD

**Issue by dotapurex1** [drtshock/PlayerVaults#222] opened 2016-08-23 05:01 UTC
Hello,

Occasionally, i'd receive reports that the player receives an internal error when trying to open their vault. When i take a look at their data. There's always this binary line in there which causes it.

  '25': !!binary |-
    eyI9PSI6Im9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFjayIsImRhbWFnZSI6MiwidHlwZSI6IkRJQU1PTkRfU1dPUkQiLCJtZXRhIjp7Ij09IjoiSXRlbU1ldGEiLCJtZXRhLXR5cGUiOiJVTlNQRUNJRklDIiwiZW5jaGFudHMiOnsiRklSRV9BU1BFQ1QiOjYsIkxPT1RfQk9OVVNfTU9CUyI6NiwiREFNQUdFX0FMTCI6MTB9LCJkaXNwbGF5LW5hbWUiOiJBIEJyb2tlbiBQcm9taXNlIPCfkpTwn5KU8J+SlPCfkpTwn5KU4p2kIiwicmVwYWlyLWNvc3QiOjF9fQ==

**Comment by kashike** [comment] 2016-08-23 05:04
This is a duplicate of #207 as far as I can see.

**Closed by kashike** 2016-08-23 05:04 UTC
Labels: duplicate
