### ISSUE TITLE
Chests overwriting own when viewing another player's contents.

### ISSUE THREAD

**Issue by mibby** [drtshock/PlayerVaults#49] opened 2014-10-22 18:16 UTC
Dev 157. http://ci.drtshock.net/job/PlayerVaults/157/

My admins have the permission node playervaults.*. I've been receiving complaints that my admins chests are being overwritten with someone else's. No one else is having this problem but my Admin team. I believe it is caused by viewing someone else's chest with /pv [player] [chest ID], then their chest contents are overwriting the admin's chest ID. Searching through the files, I have pin pointed who's chest the admins copied, and they said that they did view that person's chest.

**Comment by iBukkit** [comment] 2015-01-28 10:28
Same problem here, I've looked in someone's pv and if I now type /pv 1, It's copying the pv..

**Comment by Shmeeb** [comment] 2015-04-19 02:12
I'm also having this problem.

**Comment by drtshock** [comment] 2015-04-20 15:09
This plugin currently isn't being maintained.

**Comment by mibby** [comment] 2015-04-27 19:41
@drtshock I noticed development has picked up again per the new commits. Mind reopening this ticket?

**Comment by drtshock** [comment] 2015-04-27 20:45
Sure. Go ahead and try confirming it on the new version and give step my step instructions on how I can reproduce on my own machine please :)

**Comment by mibby** [comment] 2015-04-27 21:19
Sure thing. I'll update to the new build and retest later tonight. 

As far as instructions to reproduce the issue; as far as I'm aware and been informed by my staff, accessing an online or offline player's vault as an admin with all permissions, there is a chance it overwrites your chests to that person's vault data.

Perhaps @Theepwner @iBukkit or @Shmeeb could share their occurrence with this bug as well.

**Comment by drtshock** [comment] 2015-04-28 04:43
I know it might be hard but if you could provide /exact/ steps on how you can reproduce it every time, I can definitely fix it. Otherwise I just don't know what to look at :\

**Comment by Theepwner** [comment] 2015-04-28 08:14
Hard to find the direct steps required to replicate.

I have seen one thing though. After viewing another player's vault with /pv (name) (number), then viewing your own vault of the same number, your vault will show their items. It is copying the items, but not interacting with their vault in any way.

Does this help?

**Comment by drtshock** [comment] 2015-04-28 16:31
@Theepwner does this still happen? I believe I fixed instances of that specific issue happening as I was able to replicate it on my server as well but can't anymore.

**Comment by Theepwner** [comment] 2015-04-29 00:05
@drtshock this happens on v3.5.2 off bukkit.

**Comment by cronner** [comment] 2015-05-10 18:57
Yes still bugs with v3.5.2 :( all players lost the items, is there a way to get the content restored?

**Comment by drtshock** [comment] 2015-05-10 20:19
Duplicate of https://github.com/drtshock/PlayerVaults/issues/68 which was fixed :)
https://github.com/drtshock/PlayerVaults/commit/e931488c28e78eeef0f1109cda64530d7e678e80

**Closed by drtshock** 2015-05-10 20:19 UTC
