### ISSUE TITLE
Lag spike when player open Vault contains player's heads on 1.12.2

### ISSUE THREAD

**Issue by LapizSeller** [drtshock/PlayerVaults#364] opened 2018-06-28 10:35 UTC
PlayerVaultsX version: 4.0.1
Server software: PaperSpigot 1.12.2 Build 1467

When player open Vault contains player's heads it's make server lag spike
as i report issue on Paperspigot https://github.com/PaperMC/Paper/issues/1178#event-1705774503
they said only plugins's author can fix it: https://github.com/PaperMC/Paper/issues/991

**Comment by LapizSeller** [comment] 2018-06-28 12:20
Please fix this issue asap, i'm found that if Vault contains more than 40 player's skull server will crash

**Comment by drtshock** [comment] 2018-12-16 00:17
I'm unable to reproduce this. Can you give me any more info on this?

**Comment by drtshock** [comment] 2018-12-17 06:33
Duplicate of https://github.com/drtshock/PlayerVaults/issues/372 which has more info.

**Closed by drtshock** 2018-12-17 06:33 UTC
