### ISSUE TITLE
Could not pass event InventoryCloseEvent to PlayerVaults

### ISSUE THREAD

**Issue by mibby** [drtshock/PlayerVaults#102] opened 2015-08-15 05:03 UTC
PlayerVaults v3.5.7-b182
Spigot 1.8.8 git-Spigot-fdc1440-53fac9f

```
[20:54:01] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to PlayerVaults v3.5.7-b182
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:851) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1411) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:1) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-fdc1440-53fac9f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException: null value in entry: skull-owner=null
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaSkull.serialize(CraftMetaSkull.java:173) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:850) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	at com.drtshock.playervaults.vaultmanagement.Serialization.serialize(Serialization.java:109) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.handleSerialization(Serialization.java:119) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.serialize(Serialization.java:109) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.Serialization.toString(Serialization.java:77) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.saveVault(UUIDVaultManager.java:58) ~[?:?]
	at com.drtshock.playervaults.vaultmanagement.UUIDVaultManager.saveVault(UUIDVaultManager.java:45) ~[?:?]
	at com.drtshock.playervaults.listeners.Listeners.saveVault(Listeners.java:57) ~[?:?]
	at com.drtshock.playervaults.listeners.Listeners.onClose(Listeners.java:97) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor288.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-fdc1440-53fac9f]
	... 16 more
```

**Comment by spideyroc1** [comment] 2015-09-06 19:49
Anyone found a solution to this yet? I am getting the same error

**Comment by drtshock** [comment] 2015-09-08 14:47
Are you getting the same `Caused by: java.lang.NullPointerException: null value in entry: skull-owner=null` ?

**Comment by spideyroc1** [comment] 2015-09-08 18:03
Yes I am

**Comment by drtshock** [comment] 2015-09-08 18:05
Can you paste the vault file of that player please

**Comment by spideyroc1** [comment] 2015-09-08 20:17
This is the player's vault that reset, he has added new items to it aswell since the reset of it. He is the only one that has access to playervaults so I have not had the issue with other player's.

vault1:
  '0': '{"==":"org.bukkit.inventory.ItemStack","damage":250,"type":"DIAMOND_HELMET","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"PROTECTION_ENVIRONMENTAL":4}}}'
  '1': '{"type":"IRON_BLOCK","==":"org.bukkit.inventory.ItemStack"}'
  '2': '{"type":"GOLD_BLOCK","==":"org.bukkit.inventory.ItemStack","amount":2}'
  '3': '{"type":"EYE_OF_ENDER","==":"org.bukkit.inventory.ItemStack"}'
  '4': '{"type":"FLINT_AND_STEEL","==":"org.bukkit.inventory.ItemStack"}'
  '5': '{"type":"ARROW","==":"org.bukkit.inventory.ItemStack","amount":9}'
  '6': '{"type":"WOOD_SWORD","==":"org.bukkit.inventory.ItemStack","damage":3}'
  '7': '{"type":"WOOD_SWORD","==":"org.bukkit.inventory.ItemStack","damage":1}'
  '8': '{"type":"COOKED_BEEF","==":"org.bukkit.inventory.ItemStack","amount":32}'
  '9': '{"type":"IRON_INGOT","==":"org.bukkit.inventory.ItemStack","amount":64}'
  '10': '{"type":"SUGAR_CANE","==":"org.bukkit.inventory.ItemStack"}'
  '11': '{"type":"POTION","==":"org.bukkit.inventory.ItemStack"}'
  '12': '{"type":"NETHER_STALK","==":"org.bukkit.inventory.ItemStack"}'
  '13': '{"type":"GLASS_BOTTLE","==":"org.bukkit.inventory.ItemStack","amount":3}'
  '14': '{"type":"DIAMOND","==":"org.bukkit.inventory.ItemStack","amount":6}'
  '15': '{"==":"org.bukkit.inventory.ItemStack","damage":28,"type":"DIAMOND_SWORD","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"DAMAGE_ALL":2}}}'
  '16': '{"==":"org.bukkit.inventory.ItemStack","damage":16,"type":"DIAMOND_HELMET","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"PROTECTION_ENVIRONMENTAL":3,"DURABILITY":1}}}'
  '17': '{"==":"org.bukkit.inventory.ItemStack","damage":316,"type":"DIAMOND_HELMET","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"PROTECTION_ENVIRONMENTAL":10},"repair-cost":1}}'
  '18': '{"==":"org.bukkit.inventory.ItemStack","damage":22,"type":"DIAMOND_LEGGINGS","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"PROTECTION_ENVIRONMENTAL":2,"DURABILITY":1}}}'
  '19': '{"type":"DIAMOND_CHESTPLATE","==":"org.bukkit.inventory.ItemStack","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"PROTECTION_ENVIRONMENTAL":4,"DURABILITY":1},"repair-cost":3}}'
  '20': '{"type":"DIAMOND_HELMET","==":"org.bukkit.inventory.ItemStack","damage":7}'
  '21': '{"type":"DIAMOND_LEGGINGS","==":"org.bukkit.inventory.ItemStack","damage":3}'
  '22': '{"type":"DIAMOND_SWORD","==":"org.bukkit.inventory.ItemStack","damage":12}'
  '23': '{"type":"STICK","==":"org.bukkit.inventory.ItemStack","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"FIRE_ASPECT":2,"KNOCKBACK":2,"DAMAGE_ALL":5},"lore":["ยง3Powerful
    Wand"],"display-name":"ยงrยง4Dragon Stick"}}'
  '24': '{"type":"SUGAR","==":"org.bukkit.inventory.ItemStack","amount":4}'
  '25': '{"type":"DIAMOND_HELMET","==":"org.bukkit.inventory.ItemStack"}'
  '26': '{"==":"org.bukkit.inventory.ItemStack","damage":47,"type":"DIAMOND_CHESTPLATE","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"DURABILITY":1,"PROTECTION_PROJECTILE":1}}}'
  '27': '{"type":"DIAMOND_BOOTS","==":"org.bukkit.inventory.ItemStack","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"PROTECTION_ENVIRONMENTAL":4,"DURABILITY":1},"repair-cost":3}}'
  '28': '{"==":"org.bukkit.inventory.ItemStack","damage":22,"type":"DIAMOND_BOOTS","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"PROTECTION_PROJECTILE":1}}}'
  '29': '{"==":"org.bukkit.inventory.ItemStack","damage":60,"type":"DIAMOND_HELMET","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"PROTECTION_FIRE":1}}}'
  '30': '{"type":"DIAMOND_CHESTPLATE","==":"org.bukkit.inventory.ItemStack","damage":13}'
  '31': '{"type":"IRON_LEGGINGS","==":"org.bukkit.inventory.ItemStack","damage":52}'
  '32': '{"==":"org.bukkit.inventory.ItemStack","damage":39,"type":"CHAINMAIL_CHESTPLATE","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"PROTECTION_ENVIRONMENTAL":2}}}'
  '33': '{"==":"org.bukkit.inventory.ItemStack","damage":7,"type":"IRON_SWORD","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"DAMAGE_UNDEAD":1}}}'
  '34': '{"type":"TNT","==":"org.bukkit.inventory.ItemStack","amount":4}'
  '35': '{"type":"IRON_HELMET","==":"org.bukkit.inventory.ItemStack","damage":52}'
  '36': '{"type":"DIAMOND_BOOTS","==":"org.bukkit.inventory.ItemStack","damage":13}'
  '37': '{"type":"DIAMOND_SWORD","==":"org.bukkit.inventory.ItemStack","damage":7}'
  '38': '{"type":"GOLD_INGOT","==":"org.bukkit.inventory.ItemStack","amount":3}'
  '39': '{"==":"org.bukkit.inventory.ItemStack","damage":25,"type":"CHAINMAIL_CHESTPLATE","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"PROTECTION_ENVIRONMENTAL":2}}}'
  '40': '{"type":"DIAMOND_SWORD","==":"org.bukkit.inventory.ItemStack","damage":2}'
  '41': '{"type":"WOOL","==":"org.bukkit.inventory.ItemStack"}'
  '42': '{"type":"DIAMOND_LEGGINGS","==":"org.bukkit.inventory.ItemStack","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"PROTECTION_FIRE":2,"DURABILITY":2},"repair-cost":3}}'
  '43': '{"type":"MUTTON","==":"org.bukkit.inventory.ItemStack","amount":2}'
  '44': '{"type":"DIAMOND_SWORD","==":"org.bukkit.inventory.ItemStack","damage":11}'
  '45': '{"type":"IRON_INGOT","==":"org.bukkit.inventory.ItemStack","amount":14}'
  '46': '{"type":"GLOWSTONE_DUST","==":"org.bukkit.inventory.ItemStack","amount":3}'
  '47': '{"type":"RABBIT_HIDE","==":"org.bukkit.inventory.ItemStack"}'
  '48': '{"type":"PORK","==":"org.bukkit.inventory.ItemStack","amount":2}'
  '49': '{"type":"DIAMOND_HELMET","==":"org.bukkit.inventory.ItemStack","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"PROTECTION_ENVIRONMENTAL":1,"DURABILITY":3}}}'
  '52': '{"==":"org.bukkit.inventory.ItemStack","damage":86,"type":"DIAMOND_HELMET","meta":{"==":"ItemMeta","meta-type":"UNSPECIFIC","enchants":{"PROTECTION_ENVIRONMENTAL":4},"repair-cost":1}}'

**Comment by drtshock** [comment] 2016-05-30 21:50
Fixed in latest updates

**Closed by drtshock** 2016-05-30 21:50 UTC

**Comment by Skin0x** [comment] 2016-06-22 16:49
Hello, where is the update please ? :santa:

**Comment by drtshock** [comment] 2016-06-22 17:52
ci.drtshock.net
