### ISSUE TITLE
InventoryCloseEvent Error

### ISSUE THREAD

**Issue by CHarrisMedia** [drtshock/PlayerVaults#93] opened 2015-07-13 22:57 UTC
I've managed to get the full log you requested.

This only happens after an initial sign has been created and after that signs been created, any inventory closure brings this error:

-removed super long paste-

**Comment by CHarrisMedia** [comment] 2015-07-14 19:55
Any progress on this?

**Comment by drtshock** [comment] 2015-07-15 00:19
Did you delete their vault while they had it open? It's just null on the file.

**Comment by CHarrisMedia** [comment] 2015-07-15 00:19
No, the only person online was me and I cannot have the vault open and delete a vault. Also, no vaults were deleted at all.

**Comment by drtshock** [comment] 2015-07-15 00:23
Can you reproduce this on a fresh installation of playervaults? Do you have file permissions set correctly so the plugin can write?

**Comment by CHarrisMedia** [comment] 2015-07-15 00:24
Yes I can produce this on a vanilla server (With PEX).

**Comment by drtshock** [comment] 2015-07-15 00:26
Do that and show the full log in a gist please (hastebins expire).

**Comment by CHarrisMedia** [comment] 2015-07-15 00:29
Here, it took seconds to replicate with only PEX and PlayerVaults loaded.

https://gist.github.com/CHarrisMedia/fb9ceb6adc1558df7c0f

**Comment by CHarrisMedia** [comment] 2015-07-17 00:32
What's the progress here?

**Comment by drtshock** [comment] 2015-07-24 04:09
Can you further explain how you reproduce this? When you say initial sign, what do you mean exactly? What exactly is on the sign? Does the player have a vault before this? Have they already opened it since they just joined the server?

**Comment by CHarrisMedia** [comment] 2015-07-24 04:12
I'll explain exactly how to replicate. 

1. Create a local server just with PlayerVaults and PermissionsEx
2. Create a sign, with anything on it does not matter
3. /pvsign 1 then right click to create the sign
4. Right click the sign, everything is fine, close the vault and watch the error appear. I've replicated this multiple times to prove I'm not wrong. 

I'd also like to add, with your blocking feature, players whom are clicking quickly (putting their whole inventory into their vault) can bypass the blocking, they can then not take the blocked items from the vault.

**Comment by drtshock** [comment] 2015-07-25 19:25
Just made some changes to the signs code. If you could download the latest build and get me a stacktrace on the latest version, I'll get this resolved in the next few days. Thanks for your patience :)

**Comment by CHarrisMedia** [comment] 2015-07-25 19:28
Thanks, if you've fixed this it will have made my day! I'd also just like to reference something that can be quite important, I had one of my developers look through your handling of signs being opened and if someone gets a permission to increase the size of their vault, it doesn't update until the plugin is reloaded. The developer claimed you did some caching or something alike, I cannot remember exactly but after removing this system, if a user had the permission "playervaults.size.2" over "playervaults.size.1" the next time they opened their vault, it would be the bigger size, rather than being the same size until the plugin restarts.

**Comment by drtshock** [comment] 2015-07-26 16:57
No we don't https://github.com/drtshock/PlayerVaults/blob/master/src/main/java/com/drtshock/playervaults/listeners/SignListener.java#L96

Also, please keep each ticket to the single issue at hand. You can make more tickets if you have further issues :)

Still just waiting on the logs from the latest build with the issue reproduced.

**Comment by CHarrisMedia** [comment] 2015-07-26 16:58
Could you give me a link to the latest jar?

**Comment by drtshock** [comment] 2015-07-26 17:04
https://ci.drtshock.net/job/PlayerVaults/ build 182

**Closed** 2016-05-30 21:51 UTC
