### ISSUE TITLE
Player heads in vault and server freeze

### ISSUE THREAD

**Issue by BoredFrostbite** [drtshock/PlayerVaults#372] opened 2018-12-12 12:55 UTC
PlayerVaultsX version: 4.0.6 

Server software: 1.12.2

Details: Server sometimes freezes when a player use /pv [number], after checking the player vault, there were filled with heads (maybe the main cause?)

*I removed the paper watchdog log and timings because it was soooooo long (and pretty much not necessary).

**Comment by Frostyeiz** [comment] 2018-12-12 13:03
crap, I just found it that 4.0.6 is only for 1.13, maybe its the real cause

**Comment by ArtelGG** [comment] 2018-12-15 14:54
If you could produce an error and perhaps show your plugins and the timings report I might be able to help at least identify what's causing it.

**Comment by drtshock** [comment] 2018-12-16 00:15
Can you give us the exact contents of the inventory, your playervaults .yml file that contains this player's inventory, log files showing this, or any info on how to reproduce exactly.

**Comment by ArtelGG** [comment] 2018-12-16 02:54
@drtshock 
> 
> 
> Can you give us the exact contents of the inventory, your playervaults .yml file that contains this player's inventory, log files showing this, or any info on how to reproduce exactly.

I have a sneaking suspicion this may be an incompatibility with a player head plugin, perhaps one that allows the users to "redeem" them for money or something along those lines.

**Comment by Frostyeiz** [comment] 2018-12-16 03:46
I checked that player's vault, vault number 3 is filled with player heads.
About reproducing the freeze, I tried several times but it won't freeze anymore, maybe because I used the wrong version before (4.0.6 for 1.12.2 instead of 4.0.5, something went wrong and the server frozen)
You can see the log and timings link by looking at the edit history (I don't mind pasting it back but its length is kinda annoying for me).

[5b36d543-3dba-3c3d-857a-2162a64b90ea.zip](https://github.com/drtshock/PlayerVaults/files/2683244/5b36d543-3dba-3c3d-857a-2162a64b90ea.zip)

**Comment by ArtelGG** [comment] 2018-12-16 04:10
I did some testing on my test server with 1.8.8 and 1.12.2 PaperSpigot's, I didn't get any lag other than client end with 1.8.8, however, on 1.12.2 my server and client did hiccup a bit during the first opening of the vault. It might be an issue with how 1.9+ handles player heads.

**Comment by drtshock** [comment] 2018-12-17 06:36
Yeah just tested that vault and it gave me a little bit of a delay in populating the heads in the inventory. Not sure what the best way to handle this would be..

**Comment by ArtelGG** [comment] 2018-12-17 06:39
You could try adding the items to a load-queue if they're an instance of a skull. To load them in packs of 5 or something.

**Comment by drtshock** [comment] 2018-12-17 18:42
Perhaps, I would be concerned that we'd be open to dupes during that save window though.

**Comment by ArtelGG** [comment] 2018-12-31 05:49
You could mark them as in a vault, load the skulls, then open the inventory? It might add some delay but it'd most likely fix it.

**Comment by mbax** [comment] 2024-12-31 21:17
Should be resolved by the server at this point (And is, otherwise, a server bug).

**Closed by mbax** 2024-12-31 21:17 UTC
Labels: enhancement
