### ISSUE TITLE
Add support for block enitity tag

### ISSUE THREAD

**Issue by iaxedu** [drtshock/PlayerVaults#56] opened 2014-12-22 21:08 UTC
Please add support for block entitiy tag such as silkspawners use: http://dev.bukkit.org/bukkit-plugins/silkspawners/files/41-silk-spawners-v3-6-2-1-5-up-to-1-8/

Also add lores please :)

Thanks

**Comment by DarkPklord3** [comment] 2015-01-01 05:43
Sorry if this is bumping a dead ticket/thread, but i was just about to submit a ticket with this exact problem. After a server restart or crash, all spawners in players vaults are changed to just monster spawner's and lose the entity. (defaults to pig). Its a problem that i would imagine others are having and i think there should be some sort of fix to it :s

**Comment by drtshock** [comment] 2015-04-27 19:30
Duplicate of #62 (his ticket has more info). Please comment on there if you're still interested.

**Closed by drtshock** 2015-04-27 19:30 UTC
