### ISSUE TITLE
InventoryCloseEvent Error

### ISSUE THREAD

**Issue by CHarrisMedia** [drtshock/PlayerVaults#92] opened 2015-07-13 16:13 UTC
Are you kidding me? You've just closed my error for no reason whatsoever. Your plugin isn't throwing a "Stack trace" it's just giving that error. I take it the plugin does not work on the latest versions then? Inventories do not save upon restart and no error is being thrown, can you please explain this?

**Comment by drtshock** [comment] 2015-07-13 16:21
Duplicate of https://github.com/drtshock/PlayerVaults/issues/91

**Comment by drtshock** [comment] 2015-07-13 16:22
You can continue conversations on closed tickets.

Also note that if there is an error, there will be a stack trace unless w/e you're using as a wrapper / console modifier is removing it.

**Closed by drtshock** 2015-07-13 16:21 UTC
